#!/bin/bash

PARTI="$1"
REQS="$2"
PRS="$3"
[[ -z "$PARTI" ]] && echo "Partition name ?" && exit 1
[[ -z "$REQS" ]] && echo "ReqSize ?" && exit 1
[[ -z "$PRS" ]] && PRS=32

for FILE in a b; do
for PR in $PRS; do
for REQ in $REQS; do
for SEQ in seq rnd; do
for READ in read write; do

mount $PARTI /mnt/tmpmount &&
sleep 30 &&
nice -n 5 io /mnt/tmpmount/$FILE $READ $SEQ 180 $REQ $PR &&
nice -n 9 umount /mnt/tmpmount

[[ $? -eq 0 ]] || exit $?
sleep 30 || exit $?

done
done
done
done
done
