#!/bin/bash

if [[ $# -eq 0 ]]; then
	echo "Usage: $0 <partition> <reqsizes> <processNOs>" >&2
	exit 1
fi


PARTI="$1"
REQS="$2"
PRS="$3"
[[ -z "$PARTI" ]] && echo "Partition name ?" && exit 1
[[ -z "$REQS" ]] && echo "ReqSize ?" && exit 1
[[ -z "$PRS" ]] && PRS=32

if mount | grep -q " on $FLASHSIM_MNTPNT type "; then
	umount "$FLASHSIM_MNTPNT" || exit $?
	sleep 30
fi


for FILE in a b; do
for PR in $PRS; do
for REQ in $REQS; do
for SEQ in seq rnd; do
for READ in read write; do

mount "$PARTI" "$FLASHSIM_MNTPNT" -o noatime,nodiratime &&
sleep 30 &&
nice -n 5 io "$FLASHSIM_MNTPNT/$FILE" $READ $SEQ 180 $REQ $PR &&
nice -n 9 umount "$FLASHSIM_MNTPNT"

[[ $? -eq 0 ]] || exit $?
sleep 30 || exit $?

done
done
done
done
done
