#!/bin/bash

if [[ $# -eq 0 ]]; then
	echo "Usage: $0 <dev> <mkfscmd> <dataname>" >&2
	exit 1
fi

DEV="$1"
MKFS="$2"
DATANAME="$3"
REALUSER=$( ls -ld . | cut '-d ' -f 3 )

fdiskmkfs "$DEV" "$MKFS" &&
su -m "$REALUSER" -c "
	scp-data-to-ssd '$FLASHSIM_HOST' '$FLASHSIM_REMOTEDATAPARENT' '$FLASHSIM_MNTPNT' '$DATANAME' &&
	ln -sf '$FLASHSIM_PGCONF/postgresql.conf' '$DATANAME/postgresql.conf' &&
	ln -sf '$FLASHSIM_PGCONF/pg_hba.conf' '$DATANAME/pg_hba.conf' &&
	chmod 700 '$DATANAME' "
