#!/bin/bash

HOST="$1"
REMOTEDIR="$2"
MNTPOINT="$3"

DIR="`dirname \"$REMOTEDIR\"`"
BASE="`basename \"$REMOTEDIR\"`"
[[ -z "$MNTPOINT" ]] && MNTPOINT=/mnt/tmpmount

mkdir "$MNTPOINT/$BASE"		&&
ln -s "$MNTPOINT/$BASE" "$BASE"	&&
ssh "$HOST" "cd '$DIR' && tar cz '$BASE'" | tar xz

