#!/bin/bash

HOST="$1"
REMOTEDIR="$2"
MNTPOINT="$3"

DIR="`dirname \"$REMOTEDIR\"`"
BASE="`basename \"$REMOTEDIR\"`"
[[ -z "$MNTPOINT" ]] && MNTPOINT="/mnt/tmpmount"

mkdir -p "$MNTPOINT/$BASE"		&&
ln -sf "$MNTPOINT/$BASE" "$BASE"	&&
ssh "$HOST" "cd '$DIR' && GZIP=-1 tar cz '$BASE'" | tar xz

